{
  "extends": "algorithm.dr_cppo_constant.yaml",
  "reward_config": {
    "failure_reward": -10.0,
    "iou_coef": 0.0,
    "cd_coef": 0.0,
    "auc_coef": 0.0,
    "aoc_gms_coef": 10.0,
    "get_nc": true,
    "nc_n_points": 16384,
    "nc_tol": 5,
    "print_sample_steps": 25,
    "pool_size": 16,
    "r_mode": "10_normal_auc",
    "get_aoc_gms": true,
    "aoc_gms_n_points": 8192,
    "aoc_gms_n_angles": 125,
    "aoc_gms_rel_tol": 0.05,
    "aoc_gms_cube_trick": true,
    "aoc_gms_pc_cache_enable": false,
    "aoc_gms_upper_bound_tol_rt": 25,
    "aoc_gms_autofix_sampling": false
  }
}
