use_vllm: true
vllm_server_port: 8000
bf16: true
gradient_checkpointing: true
remove_unused_columns: false
ddp_find_unused_parameters: false
beta: 0
weight_decay: 0
# GRPOConfig defaults

output_dir: models/test_auc_gms
per_device_train_batch_size: 4
gradient_accumulation_steps: 1

max_completion_length: 1400

log_completions: false
logging_steps: 30
# valid if using one device, otherwise adjust generation_batch_size
num_generations: 16
generation_batch_size: 64
report_to: ["comet_ml"]
run_name: grpo_auc_gms_0
num_train_epochs: 20
save_strategy: steps
save_steps: 100

temperature: 1.0
top_p: 0.99
top_k: 50
importance_sampling_level: sequence
loss_type: dr_grpo
epsilon: 0.1
num_iterations: 3
scale_rewards: false

learning_rate: 3e-5

# RewardArgs (see `rl_train.py:RewardArgs` / `rewards.py`)
failure_reward: -10
iou_coef: 0
cd_coef: 0
auc_coef: 0
aoc_gms_coef: 10

# ---- AUC GMS metric params (optional) ----
get_aoc_gms: true
aoc_gms_n_points: 8192
aoc_gms_n_angles: 125
aoc_gms_rel_tol: 0.05
aoc_gms_cube_trick: true
aoc_gms_pc_cache_enable: false
aoc_gms_upper_bound_tol_rt: 25
aoc_gms_autofix_sampling: false

# ---- Normal consistency metric params (optional) ----
get_nc: true
nc_n_points: 16384
nc_tol: 5

# ---- Reward plumbing / logging ----
print_sample_steps: 25
pool_size: 16
r_mode: "10_normal_auc"

# TrainingArgs (see `rl_train.py:TrainingArgs`)
clip_cov: false
top_samples: 4